name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache CocoaPods files
        uses: actions/cache@v1
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - run: pod install
      - name: Build
        run: xcodebuild -workspace RealmToDo.xcworkspace -scheme RealmToDo -configuration Debug -sdk iphonesimulator
        
      - name: Make Artefact
        run: |
          zip artefact.zip App.ipa App.app.dSYM.zip
      - uses: actions/upload-artifact@v1
        with:
          name: artefact.zip
          path: ./artefact.zip
          
      - name: Distribute App
        run: |
          curl \
          -H "Authorization: token ${{secrets.DEPLOY_GATE_API_KEY}}" \
          -F "file=@./artefact.zip" \
          -F "message=${{github.event.pull_request.title}}
          ${{github.event.pull_request.body}}" \
          "https://deploygate.com/api/users/${{secrets.DEPLOY_GATE_USER_NAME}}/apps"
